name: 'My application'


sources:
  bower: true
  bundler: false

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc


ignored:
  bundler:
    - some-internal-gem

  bower:
    - some-internal-package


reviewed:
  bundler:
    - bcrypt-ruby

  bower:
  - classlist # public domain
  - octicons
