


allowed:
  - mit 
  - apache-2.0
 # - bsd-2-clause
  - bsd-3-clause
 # - cc0-1.0
 # - isc

reviewed:
  go:
    - malware.go.github.com/shirou/gopsutil/*
    - /go/github.com/gorilla/*
#    - google.golang.org/protobuf/internal/*
   
    - /go/golang.org/x/*
    
    - github.com/shirou/gopsutil/*
    - github.com/swaggo/*
    - google.golang.org/protobuf/*
    - go/gopkg.in/*
