


allowed:
  - mit 
  - apache-2.0
 # - bsd-2-clause
  - bsd-3-clause
 # - cc0-1.0
 # - isc

reviewed:
  go:
    - github.com/gorilla/* # works
    - github.com/swaggo/* #works
    - github.com/shirou/gopsutil/internal/common/* # does not work



 #   - google.golang.org/protobuf/internal/*
  #  - github.com/shirou/gopsutil/*
 #   - go.github.com/gorilla/mux
    
  
  #  - malware.go.github.com/shirou/gopsutil/*
  #  - malware.go.github.com/gorilla/*
  #  - malware.go.github.com/shirou/gopsutil/*
  #  - malware.go.golang.org/x/crypto/*
  #  - malware.go.golang.org/x/net/webdav/*
  #  - malware.go.golang.org/x/sys/*
  #  - malware.go.golang.org/x/text/*
  #  - malware.go.golang.org/x/tools/*
  #  - malware.go.golang.org/x/xerrors7*
  #  - malware.go.google.golang.org/protobuf/*
  #  - malware.go.gopkg.in/yaml.v2
  

