# also works with pull_request event
on:
  push:
    branches: [main]
    
jobs:
  licensed:
    runs-on: ubuntu-latest    
    steps:
    - run: python3 --version # install dependencies in local environment
    - run:  |
         sudo add-apt-repository ppa:deadsnakes/ppa \
         && sudo apt update \
         && sudo apt install python3.6
         sudo apt install python3.6-dev bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libpopt0
         mkdir tmp
         wget -O tmp/virtualenv.pyz https://bootstrap.pypa.io/virtualenv/virtualenv.pyz
         python3 tmp/virtualenv.pyz tmp
         source tmp/bin/activate
         pip install scancode-toolkit
         scancode -l . --json-pp licenseReport.json

