# also works with pull_request event
on:
  push:
    branches: [main]
    
jobs:
  licensed:
    runs-on: ubuntu-latest    
    steps:
    - run: python3 --version # install dependencies in local environment
    - run:  |
         sudo apt install python3.6
         sudo apt install python3.6-dev bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libpopt0
