# also works with pull_request event
on:
  push:
    branches: [main]
    
jobs:
  licensed:
    runs-on: ubuntu-latest    
    steps:
    - run: python3 --version # install dependencies in local environment
