# also works with pull_request event
on:
  push:
    branches: [main]
    
jobs:
  licensed:
    runs-on: ubuntu-latest    
    steps:
    # if using actions/checkout at major version 2 or greater,
    # please set fetch-depth to a high number, or to 0.
    # running this action can require access to more than just the latest commit on a branch
    - run: |
        curl -sSL https://github.com/github/licensed/releases/download/<version>/licensed-<version>-<os>-x64.tar.gz > licensed.tar.gz
        echo hi
