
name: "Update and check dependency data"


on:
  push:
    branches: [main]


jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v1
      - uses: jonabc/setup-licensed@v1
        with:
         version: 2.x
         
      - run: bundle install
         
      - run: go get "golang.org/x/tools/go/loader"
         
      - run: licensed status
