name: licenseTest
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  licenseTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x' # required: must satisfy semver.validRange
    - run: npm install # install dependencies in local environment
    - run: licensed list

