name: licenseTest
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  licenseTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
    # if using actions/checkout at major version 2 or greater,
    # please set fetch-depth to a high number, or to 0.
    # running this action can require access to more than just the latest commit on a branch
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - run: bundle install
    - uses: jonabc/licensed-ci@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        command: 'bundle exec licensed' # or bin/licensed when using binstubs

