
name: "Update and check dependency data"


on:
  push:
    branches: [main]


jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{github.ref}} # checkout branch not SHA

    - run: npm install --production

    - name: Run setup-licensed
      uses: ./
      with:
        version: '2.x'
        github_token: ${{ secrets.GITHUB_TOKEN }}

 
